#!/usr/bin/env bash

set -euo pipefail

EJSON2ENV_PLUGIN_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")"; cd ..; pwd)
EJSON2ENV_BIN_PATH="$EJSON2ENV_PLUGIN_ROOT/ejson2env"
BUILDKITE_PLUGIN_EJSON2ENV_EJSON_FILE="${BUILDKITE_PLUGIN_EJSON2ENV_EJSON_FILE:-.buildkite/secrets.ejson}"
BUILDKITE_PLUGIN_EJSON2ENV_EJSON_PRIVATE_KEY_ENV_KEY="${BUILDKITE_PLUGIN_EJSON2ENV_EJSON_PRIVATE_KEY_ENV_KEY:-EJSON_PRIVATE_KEY}"

ejson_exports() {
  echo "${!BUILDKITE_PLUGIN_EJSON2ENV_EJSON_PRIVATE_KEY_ENV_KEY}" | \
    $EJSON2ENV_BIN_PATH --key-from-stdin "$BUILDKITE_PLUGIN_EJSON2ENV_EJSON_FILE"
}

export_secrets() {
  local export_lines
  if export_lines="$(ejson_exports)"; then
    eval "$export_lines"
  else
    echo "Failed to export EJSON secrets from $BUILDKITE_PLUGIN_EJSON2ENV_EJSON_FILE"
    exit 1
  fi
}

export_secrets

if [ "${EJSON2ENV_TEST_MODE:-false}" == "true" ]; then
  if [ -n "${EJSON2ENV_TEST_VERIFY_KEY:-}" ]; then
    echo "Verifying env var ${EJSON2ENV_TEST_VERIFY_KEY} matches $EJSON2ENV_TEST_VERIFY_VALUE"
    if [ ! "${!EJSON2ENV_TEST_VERIFY_KEY}" == "$EJSON2ENV_TEST_VERIFY_VALUE" ]; then
      echo "\"$EJSON2ENV_TEST_VERIFY_KEY\" does not match \"$EJSON2ENV_TEST_VERIFY_VALUE\""
      exit 1
    fi
  fi
fi
