#!/usr/bin/env bash

set -euo pipefail

EJSON2ENV_PLUGIN_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")"; cd ..; pwd)

arch="$(arch)"
case "$arch" in
  arm*|aarch64)
    arch="arm64";;
  x86_64|amd64)
    arch="amd64";;
  *)
    echo "Unsupported architecture: $arch"
    exit 1
esac

os=$OSTYPE

case "$os" in
  linux*)
    os="linux";;
  darwin*)
    os="darwin";; 
  bsd*)
    os="freebsd";; 
  *)
    echo "Unsupported OS: $OSTYPE"
    exit 1
esac

if [[ $os == 'darwin' ]]; then
  EJSON2ENV_BIN_PATH="$EJSON2ENV_PLUGIN_ROOT/ejson2env-darwin-all"
else
  EJSON2ENV_BIN_PATH="$EJSON2ENV_PLUGIN_ROOT/ejson2env-${os}-${arch}"
fi


BUILDKITE_PLUGIN_EJSON2ENV_EJSON_FILE="${BUILDKITE_PLUGIN_EJSON2ENV_EJSON_FILE:-.buildkite/secrets.ejson}"
BUILDKITE_PLUGIN_EJSON2ENV_EJSON_PRIVATE_KEY_ENV_KEY="${BUILDKITE_PLUGIN_EJSON2ENV_EJSON_PRIVATE_KEY_ENV_KEY:-EJSON_PRIVATE_KEY}"

validate_config() {
  if [ ! -f "${BUILDKITE_PLUGIN_EJSON2ENV_EJSON_FILE}" ]; then
    echo "ejson_file not found at \"$BUILDKITE_PLUGIN_EJSON2ENV_EJSON_FILE\""
    exit 1
  fi
  if [ "${!BUILDKITE_PLUGIN_EJSON2ENV_EJSON_PRIVATE_KEY_ENV_KEY:-}" == "" ]; then
    echo "ejson_private_key_env_key \"$BUILDKITE_PLUGIN_EJSON2ENV_EJSON_PRIVATE_KEY_ENV_KEY\" is empty or not set"
    exit 1
  fi
}

ejson_exports() {
  echo "${!BUILDKITE_PLUGIN_EJSON2ENV_EJSON_PRIVATE_KEY_ENV_KEY}" | \
    $EJSON2ENV_BIN_PATH --key-from-stdin "$BUILDKITE_PLUGIN_EJSON2ENV_EJSON_FILE"
}

export_secrets() {
  local export_lines
  if export_lines="$(ejson_exports)"; then
    eval "$export_lines"
  else
    echo "Failed to export EJSON secrets from $BUILDKITE_PLUGIN_EJSON2ENV_EJSON_FILE"
    exit 1
  fi
}

validate_config
export_secrets

if [ "${EJSON2ENV_TEST_MODE:-false}" == "true" ]; then
  if [ -n "${EJSON2ENV_TEST_VERIFY_KEY:-}" ]; then
    echo "Verifying env var ${EJSON2ENV_TEST_VERIFY_KEY} matches $EJSON2ENV_TEST_VERIFY_VALUE"
    if [ ! "${!EJSON2ENV_TEST_VERIFY_KEY}" == "$EJSON2ENV_TEST_VERIFY_VALUE" ]; then
      echo "\"$EJSON2ENV_TEST_VERIFY_KEY\" does not match \"$EJSON2ENV_TEST_VERIFY_VALUE\""
      exit 1
    fi
  fi
fi
